version: '3.4'

services:
  client:
    build: client
    volumes:
      - /app/node_modules
      - ./client:/app
    env_file: .env
    ports:
      - 3000
        
  server:
    build: server
    env_file: .env
    depends_on:
      - mongo
    volumes:
      - /app/node_modules
      - ./server:/app
    ports:
      - 3000

  api-user:
    build: api-user
    env_file: .env
    depends_on:
      - postgres
    volumes:
      - /app/node_modules
      - ./api-user:/app
    ports:
      - 3000

  mongo:
    image: mongo
    env_file: .env
    ports:
      - 27017
      
  postgres:
    image: postgres
    env_file: .env
    ports: 
      - 5432

  nginx:
    build: nginx
    container_name: nginx
    restart: 'on-failure'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/html:/etc/nginx/html
    depends_on:
      - server
      - api-user
      - client
    ports:
      - 80:80
      - 443:443