export const AUTH_USER = 'AUTH_USER'
export const LOGOUT = 'LOGOUT'

export const SUCCESS_MESSAGE = 'SUCCESS_MESSAGE'
export const WARN_MESSAGE = 'WARN_MESSAGE'
export const INFO_MESSAGE = 'INFO_MESSAGE'

export const ERROR = 'ERROR'
export const LOADING = 'LOADING'
export const DONE_LOADING = 'DONE_LOADING'

export const GET_USER_PROFILE = 'GET_USER_PROFILE'
export const USER_LOGOUT = 'USER_LOGOUT'

export const SET_USER = 'SET_USER'

export const SET_TERM = 'SET_TERM'
export const SET_RESOURCE = 'SET_RESOURCE'
export const SET_RESOURCE_LIST = 'SET_RESOURCE_LIST'

export const SET_SELECTION = 'SET_SELECTION'
export const SET_SEARCH_RESULT = 'SET_SEARCH_RESULT'

export const SET_CHOOSEN_ELEMENT = 'SET_CHOOSEN_ELEMENT'
export const SET_OTHER_ELEMENT = 'SET_OTHER_ELEMENT'
export const REMOVE_OTHER_ELEMENT = 'REMOVE_OTHER_ELEMENT'
